#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale --randomize ~/bg/*
bspc monitor -d I II III IV V VI VII VIII IX X
~/.config/bspwm/polybar_launch.sh
compton --config /home/majkel/.config/compton/compton.conf
dunst
xflux -l 51.473134 -g 19.678447
xinput --set-prop 10 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 14 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 14 'libinput Accel Speed' 1
setxkbmap -layout pl
xautolock -time 20 -locker 'systemctl suspend' -detectsleep -notify 30 -notifier "notify-send -u critical -t 60000 -- 'Lock in 1 min'" -corners ---
bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# borders
bspc config focused_border_color "#d16ae6"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
