#!/bin/bash



keyhl=e77cdb7f
bshl=582da37f
	font="sans-serif"
	locktext='Type password to unlock...'
	wallpaper_cmd='feh --bg-fill --no-fehbg'

rectangles=" "

SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
for RES in $SR; do
  SRA=(${RES//[x+]/ })
  CX=$((${SRA[2]} + 25))
  CY=$((${SRA[1]} - 80))
  rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
done

BLURTYPE="4x8"
TMPBG=/tmp/screen.png
scrot $TMPBG && convert $TMPBG -blur $BLURTYPE $TMPBG
i3lock \
		--timepos='x+640:h-500' \
		--datepos='x+600:h-400' \
		-i $TMPBG\
  --clock --datestr "Type password to unlock..." \
  --insidecolor=00000000 --ringcolor=#321738 --line-uses-inside \
  --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
  --insidevercolor=#321738 --insidewrongcolor=d23c3dff \
  --ringvercolor=#801275 --ringwrongcolor=ffffffff --indpos="x+650:h-330" \
  --radius=100 --ring-width=3 --veriftext="" --wrongtext="" \
  
rm $TMPBG






